language: objective-c
cache: bundler
env:
  - HOMEBREW_NO_INSTALL_CLEANUP=1

matrix:
  include:
  - name: "Test Formulae"
    osx_image: xcode10.2
    env: TEST_SUITE=brew
  - name: "Test Casks"
    osx_image: xcode10.2
    env: TEST_SUITE=cask

script:
  - ./test.sh $TEST_SUITE

branches:
  only:
  - master
