# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitOpen < Formula
  desc "Opens your Git repository in your browser"
  homepage "https://github.com/arbourd/git-open"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arbourd/git-open/releases/download/v0.3.0/git-open-v0.3.0-darwin-amd64.tar.gz"
      sha256 "368851e0054a37d86e328cee37f02630f3140709f89bb75039c03e049d6f8350"

      define_method(:install) do
        bin.install "git-open"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arbourd/git-open/releases/download/v0.3.0/git-open-v0.3.0-darwin-arm64.tar.gz"
      sha256 "b0c627607bdcc105129a808518032bd765298d0b41d776bd2ece3030c63beb54"

      define_method(:install) do
        bin.install "git-open"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arbourd/git-open/releases/download/v0.3.0/git-open-v0.3.0-linux-amd64.tar.gz"
      sha256 "c1b64ad2ebfdc9acfb92d98e64b03b20365a411c1d7b440396da211ddee94087"
      define_method(:install) do
        bin.install "git-open"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arbourd/git-open/releases/download/v0.3.0/git-open-v0.3.0-linux-arm64.tar.gz"
      sha256 "6d55405dbc9d4a8d3f68403e102b8f9d3ab6451cba82b640e64d0ddaffb697a2"
      define_method(:install) do
        bin.install "git-open"
      end
    end
  end

  conflicts_with "git-open"

  test do
    system "git", "clone", "https://github.com/arbourd/git-open.git"

    cd "git-open" do
      assert_match "Opening https://github.com/arbourd/git-open",
                  shell_output("#{bin}/git-open")
      assert_match "Opening https://github.com/arbourd/git-open/tree/main/LICENSE",
                  shell_output("#{bin}/git-open LICENSE")
      assert_match "Opening https://github.com/arbourd/git-open/commit/71e081deeb92764e1bae203419ac72de1d935d2f",
                  shell_output("#{bin}/git-open 71e081deeb92764e1bae203419ac72de1d935d2f")
    end
  end
end
