# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSync < Formula
  desc "Updates your branches"
  homepage "https://github.com/arbourd/git-sync"
  version "0.2.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arbourd/git-sync/releases/download/v0.2.5/git-sync-v0.2.5-darwin-amd64.tar.gz"
      sha256 "c02cd2eea89eaaa90224bb4ac9c4a33da6e0b9fa1822f9baa42aee294f633f46"

      def install
        bin.install "git-sync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arbourd/git-sync/releases/download/v0.2.5/git-sync-v0.2.5-darwin-arm64.tar.gz"
      sha256 "bf31e7234db41bcfcfc7f8965989f4da2f969459478a6933eab0db4801a9ebc3"

      def install
        bin.install "git-sync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/arbourd/git-sync/releases/download/v0.2.5/git-sync-v0.2.5-linux-amd64.tar.gz"
      sha256 "eb4aaf009d6acb6f9f11f240ad00018f1e2d36144e1e6e89ce309e1e42913609"

      def install
        bin.install "git-sync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arbourd/git-sync/releases/download/v0.2.5/git-sync-v0.2.5-linux-arm64.tar.gz"
      sha256 "db0e697af75dcbd05b32b1f027e2a626787e1d1d46cb642f3f8ac85627392358"

      def install
        bin.install "git-sync"
      end
    end
  end

  conflicts_with "git-extras"
  conflicts_with "git-sync"

  test do
    system "git", "clone", "https://github.com/arbourd/git-sync.git"

    cd "git-sync" do
      system "git", "reset", "--hard", "HEAD~1"
      sha = shell_output("git rev-parse HEAD")

      assert_match sha[0..6], shell_output("#{bin}/git-sync")
      refute_equal sha, shell_output("git rev-parse HEAD")
    end
  end
end
