# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitGet < Formula
  desc "Go gets your code"
  homepage "https://github.com/arbourd/git-get"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/arbourd/git-get/releases/download/v0.3.1/git-get-v0.3.1-darwin-arm64.tar.gz"
      sha256 "b22988dbcbe9c382c1ad7ecb7c6650b8d271ff9ab8519ba82088ce6a1d13e158"

      def install
        bin.install "git-get"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/arbourd/git-get/releases/download/v0.3.1/git-get-v0.3.1-darwin-amd64.tar.gz"
      sha256 "2d7485cb2a726f56b25ddc25d1c2270966b5a7c90f58dee0e25ec56e96e948b7"

      def install
        bin.install "git-get"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arbourd/git-get/releases/download/v0.3.1/git-get-v0.3.1-linux-arm64.tar.gz"
      sha256 "4364f235da1190f8b814adf0e2f442368f5ca9fe498a022bec68a1f640909b85"

      def install
        bin.install "git-get"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/arbourd/git-get/releases/download/v0.3.1/git-get-v0.3.1-linux-amd64.tar.gz"
      sha256 "47e9447e73a3b6b4ebeda9b38ccab4b43234c3f07793e8a6c7ca84cf3d2ee0b8"

      def install
        bin.install "git-get"
      end
    end
  end

  test do
    assert_match "#{testpath}/src/github.com/arbourd/git-get",
                 shell_output("#{bin}/git-get github.com/arbourd/git-get")
  end
end
