# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSync < Formula
  desc "Updates your branches"
  homepage "https://github.com/arbourd/git-sync"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arbourd/git-sync/releases/download/v0.2.1/git-sync-v0.2.1-darwin-amd64.tar.gz"
      sha256 "a992f7b891f368175f25602411b9608fc45a6552d371566f2b3ca9bd2d047c17"

      def install
        bin.install "git-sync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arbourd/git-sync/releases/download/v0.2.1/git-sync-v0.2.1-darwin-arm64.tar.gz"
      sha256 "49d5ff5fa7ad227c7db44d4a4b1e3aa8e85dc9f3c3054a3b32467466a7b5af3b"

      def install
        bin.install "git-sync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/arbourd/git-sync/releases/download/v0.2.1/git-sync-v0.2.1-linux-amd64.tar.gz"
      sha256 "c3487f1799e1463abd595d2ec1313d27e2d7ecd3963c9a78957886873a02e4cf"

      def install
        bin.install "git-sync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arbourd/git-sync/releases/download/v0.2.1/git-sync-v0.2.1-linux-arm64.tar.gz"
      sha256 "1c3f875747a273261dfb2fa9044d1b2ee13b4f6eac198e23257041b2579f0007"

      def install
        bin.install "git-sync"
      end
    end
  end
end
