# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSync < Formula
  desc "Updates your branches"
  homepage "https://github.com/arbourd/git-sync"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arbourd/git-sync/releases/download/v0.3.0/git-sync-v0.3.0-darwin-amd64.tar.gz"
      sha256 "565414dfbee646ff496e04a6600d829fe11c8bf40a2fea718060214dd6751236"

      define_method(:install) do
        bin.install "git-sync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arbourd/git-sync/releases/download/v0.3.0/git-sync-v0.3.0-darwin-arm64.tar.gz"
      sha256 "a9e67276daa30b7cdc40e519396c4073f8b6274ab3f50fb2e46585d37f95307c"

      define_method(:install) do
        bin.install "git-sync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arbourd/git-sync/releases/download/v0.3.0/git-sync-v0.3.0-linux-amd64.tar.gz"
      sha256 "06d44f442e2eba9762d0db1ed7e32f6af1fee87586c0d5ed41fca4dc978cf8c0"
      define_method(:install) do
        bin.install "git-sync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arbourd/git-sync/releases/download/v0.3.0/git-sync-v0.3.0-linux-arm64.tar.gz"
      sha256 "36f4ef3fcfda04fbb1d0415efe3a14ddb9abd89c9099c5f538b7e89f6ab38c01"
      define_method(:install) do
        bin.install "git-sync"
      end
    end
  end

  conflicts_with "git-extras"
  conflicts_with "git-sync"

  test do
    system "git", "clone", "https://github.com/arbourd/git-sync.git"

    cd "git-sync" do
      system "git", "reset", "--hard", "HEAD~1"
      sha = shell_output("git rev-parse HEAD")

      assert_match sha[0..6], shell_output("#{bin}/git-sync")
      refute_equal sha, shell_output("git rev-parse HEAD")
    end
  end
end
