# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitOpen < Formula
  desc "Opens your webbrowser"
  homepage "https://github.com/arbourd/git-open"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arbourd/git-open/releases/download/v0.1.0/git-open-v0.1.0-darwin-amd64.tar.gz"
      sha256 "0f9463b04817f7aaa6200b0145a1b6681e191c19a1a01c231d5720c3db0ea2d6"

      def install
        bin.install "git-open"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arbourd/git-open/releases/download/v0.1.0/git-open-v0.1.0-darwin-arm64.tar.gz"
      sha256 "e517d71e47aa32b9f41088db37f274a12af2aaeed6406b7c000c78f5d830c6a9"

      def install
        bin.install "git-open"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arbourd/git-open/releases/download/v0.1.0/git-open-v0.1.0-linux-arm64.tar.gz"
      sha256 "0c176437bcf020bedb6b43697129ac36fb18ee1b97251345f52989797c664cd7"

      def install
        bin.install "git-open"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/arbourd/git-open/releases/download/v0.1.0/git-open-v0.1.0-linux-amd64.tar.gz"
      sha256 "69f6c5e1f7ed2e71d6a09452daeeda4795f991ad330151a873fea77cd65b7a18"

      def install
        bin.install "git-open"
      end
    end
  end

  conflicts_with "git-open"

  test do
    system "git", "clone", "https://github.com/arbourd/git-open.git"

    cd "git-open" do
      assert_match "Opening https://github.com/arbourd/git-open",
                   shell_output("#{bin}/git-open")
      assert_match "Opening https://github.com/arbourd/git-open/tree/main/LICENSE",
                   shell_output("#{bin}/git-open LICENSE")
      assert_match "Opening https://github.com/arbourd/git-open/commit/71e081deeb92764e1bae203419ac72de1d935d2f",
                   shell_output("#{bin}/git-open 71e081deeb92764e1bae203419ac72de1d935d2f")
    end
  end
end
