# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trash < Formula
  desc "Safely move items to macOS trash asynchronously"
  homepage "https://github.com/arbourd/trash"
  version "0.3.7"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/arbourd/trash/releases/download/v0.3.7/trash-v0.3.7-darwin-amd64.tar.gz"
    sha256 "200bac02fd8f1824d4acc888195e3d7f6631ca3405ae91a4b5113d8638e1f4aa"

    def install
      bin.install "trash"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/arbourd/trash/releases/download/v0.3.7/trash-v0.3.7-darwin-arm64.tar.gz"
    sha256 "e9b48ca19f82d18525e36d839d8bfdac2c3c86c18d1c44a355fcdb3891f8977e"

    def install
      bin.install "trash"
    end
  end

  conflicts_with "macos-trash"
  conflicts_with "trash"
  conflicts_with "trash-cli"

  test do
    assert_match "trash, version #{version}", shell_output("#{bin}/trash --version")
  end
end
