# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trash < Formula
  desc "Safely move items to macOS trash"
  homepage "https://github.com/arbourd/trash"
  version "0.3.6"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/arbourd/trash/releases/download/v0.3.6/trash-v0.3.6-darwin-arm64.tar.gz"
      sha256 "035330cdfc4376146e691932e9f4424b93c8d5e17355a678dc7aa9dcaf9b86c3"

      def install
        bin.install "trash"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/arbourd/trash/releases/download/v0.3.6/trash-v0.3.6-darwin-amd64.tar.gz"
      sha256 "6d08553767fd22cdd777080873d104a995999d6fe22264eafc2d9cf2adfa22bd"

      def install
        bin.install "trash"
      end
    end
  end

  conflicts_with "macos-trash"
  conflicts_with "trash"
  conflicts_with "trash-cli"

  test do
    assert_match "trash, version #{version}", shell_output("#{bin}/trash --version")
  end
end
