# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trash < Formula
  desc "Safely move items to macOS trash"
  homepage "https://github.com/arbourd/trash"
  version "0.3.5"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/arbourd/trash/releases/download/v0.3.5/trash-v0.3.5-darwin-arm64.tar.gz"
      sha256 "34458aefd885c4512a6a42b8491d4254a9aec4c6b606b4e4d5a718fcfaa082e3"

      def install
        bin.install "trash"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/arbourd/trash/releases/download/v0.3.5/trash-v0.3.5-darwin-amd64.tar.gz"
      sha256 "23cce0ccb054d382d0d9b4dffcd5400cd31c50044e8387291b5b99150df785a7"

      def install
        bin.install "trash"
      end
    end
  end

  conflicts_with "trash"
  conflicts_with "trash-cli"

  test do
    assert_match "trash, version #{version}", shell_output("#{bin}/trash --version")
  end
end
