name: ci

on:
  push:
    paths:
    - .github/workflows/formula.yml
    - Formula/**

jobs:
  formula:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]
    env:
      GITHUB_ACTIONS_HOMEBREW_SELF_HOSTED: 1
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
    defaults:
      run:
        working-directory: Formula

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: cache
      with:
        path: /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby
        key: ${{ runner.os }}-rubygems-${{ hashFiles('/usr/local/Homebrew/Library/Homebrew/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-rubygems-

    - run: brew install-bundler-gems
    - run: brew test-bot --only-formulae *.rb
