name: formula

on:
  push:
    paths:
    - .github/workflows/formula.yml
    - Formula/**

jobs:
  ci:
    runs-on: macos-latest
    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
    defaults:
      run:
        working-directory: Formula

    steps:
    - uses: actions/checkout@v1

    - name: Cache Bundler RubyGems
      id: cache
      uses: actions/cache@v1
      with:
        path: /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby
        key: rubygems-${{ hashFiles('/usr/local/Homebrew/Library/Homebrew/Gemfile.lock') }}
        restore-keys: rubygems-

    - name: Install Bundler RubyGems
      if: steps.cache.outputs.cache-hit != 'true'
      run: brew install-bundler-gems

    - name: Brew audit
      run: brew audit --strict ./*.rb

    - name: Brew install
      run: brew install --build-from-source ./*.rb

    - name: Brew test
      run: brew test ./*.rb
