name: go

on:
  pull_request:
    paths:
      - .github/workflows/go-build.yml
      - go.*
      - main.go
      - main_test.go
  push:
    paths:
      - .github/workflows/go-build.yml
      - go.*
      - main.go
      - main_test.go
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          cache: false
          go-version-file: go.mod

      - run: go vet ./...
      - run: go build .
      - run: go test ./... -v -race
      - run: go run .
