name: go

on:
  pull_request:
    paths:
      - .github/workflows/go-update.yml
  push:
    paths:
      - .github/workflows/go-update.yml
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          cache: false
          go-version-file: go.mod

      - name: Run go update
        id: go
        run: |
          echo "Generating Go formula"
          formula=$(go run .)

          echo "::group::formula"
          echo "${formula}"
          echo "::endgroup::"

          echo "${formula}" > Formula/go.rb
          version=$(echo "$formula" | grep -oP 'version "\K\d+\.\d+\.\d+')

          echo "version=$version"
          echo "version=${version}" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: github.event_name != 'pull_request'
        uses: peter-evans/create-pull-request@v7
        with:
          branch: go-${{ steps.go.outputs.version }}
          commit-message: Go v${{ steps.go.outputs.version }}
          title: Go v${{ steps.go.outputs.version }}
          body: |
            https://go.dev/doc/devel/release#go${{ steps.go.outputs.version }}
          reviewers: arbourd
          token: ${{ secrets.GITHUB_TOKEN }}
