name: go

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache: true
          go-version-file: go.mod

      - name: go update
        id: go
        run: |
          formula=$(go run .)
          echo "$formula"

          version=$(echo "$formula" | grep -oP 'version "\K\d+\.\d+\.\d+')
          echo "$version"
          echo "version=${version}" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: go-${{ steps.go.outputs.version }}
          commit-message: Go v${{ steps.go.outputs.version }}
          title: Go v${{ steps.go.outputs.version }}
          body: |
            https://go.dev/doc/devel/release#go${{ steps.go.outputs.version }}
          reviewers: arbourd
          token: ${{ secrets.GITHUB_TOKEN }}
