name: go

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Cache Go mods
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: go mod download

      - name: go update
        id: go
        run: |
          VERSION=$(go run .)
          MINOR_VERSION=$(echo $VERSION | grep -oP '^\d+\.\d+')
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=minor-version::$MINOR_VERSION"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: go-${{ steps.go.outputs.version }}
          commit-message: Go v${{ steps.go.outputs.version }}
          title: Go v${{ steps.go.outputs.version }}
          body: |
            https://go.dev/doc/devel/release#go${{ steps.go.outputs.minor-version }}
          reviewers: arbourd
          token: ${{ secrets.GITHUB_TOKEN }}
