name: CI

on:
  push:
    paths:
    - 'Casks/**'
    - 'Formula/**'

jobs:
  make:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build, install and test Brew packages
      run:  make test-brew
